name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=10s --health-retries=3

    steps:
      # Kodni yuklash
      - name: Checkout Code
        uses: actions/checkout@v3

      # PHP-ni sozlash
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # PHP versiyasini loyihangizga moslang
          extensions: pdo_mysql # MySQL kengaytmasini yoqing
          ini-values: post_max_size=256M # PHP konfiguratsiyasi
          coverage: xdebug # Kod qamrovini o'lchash uchun Xdebug

      # PHP kutubxonalarini o'rnatish
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # `.env.testing` faylini sozlash
      - name: Set up Application Environment
        run: |
          cp .env.example .env
          cp .env.testing .env # .env.testing faylini qo'lda yuklash

      # Artisan asosiy sozlamalari
      - name: Generate Application Key
        run: php artisan key:generate --env=testing

      # Ma'lumotlar bazasini yaratish va migratsiyalarni bajarish
      - name: Run Database Migrations
        run: php artisan migrate --env=testing

      # PHPUnit testlarini ishlatish
      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --testdox
